# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gensdujardin', '0002_auto_20160427_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='description',
            new_name='presentation',
        ),
    ]
