# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 09:02
from __future__ import unicode_literals

import apps.jardin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création', verbose_name='Date de création')),
            ],
        ),
        migrations.CreateModel(
            name='Lopin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du lopin', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la plante', max_length=20, verbose_name='Nom de la plante')),
                ('image', models.ImageField(upload_to=apps.jardin.models.content_file_name_plante)),
                ('espece', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('lopin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardin.Lopin')),
            ],
        ),
        migrations.AddField(
            model_name='jardin',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='jardin',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='ville',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='lopin',
            name='jardin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardin.Jardin'),
        ),
        migrations.AddField(
            model_name='actualite',
            name='jardin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardin.Jardin'),
        ),
    ]
