# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 09:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0002_auto_20160426_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=10)),
                ('code_postal', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être composé de 10 chiffres.', regex='^\\d{5}$')], verbose_name='Code postal')),
                ('rue', models.CharField(max_length=20)),
                ('long', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='jardin',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='jardin',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='jardin',
            name='long',
        ),
        migrations.RemoveField(
            model_name='jardin',
            name='rue',
        ),
        migrations.RemoveField(
            model_name='jardin',
            name='ville',
        ),
        migrations.AddField(
            model_name='jardin',
            name='adresse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jardin.Adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lopin',
            name='adresse',
            field=models.ForeignKey(default=None, help_text="Adresse du lopin. Cette adresse doit être égale à l'adresse du jardin si le lopin se trouve dans un jardin", on_delete=django.db.models.deletion.CASCADE, to='jardin.Adresse'),
            preserve_default=False,
        ),
    ]
