# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0003_auto_20160426_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='rue',
            field=models.CharField(max_length=200),
        ),
    ]
