# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0004_auto_20160426_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='ville',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='nom',
            field=models.CharField(help_text='Nom de la ville où se trouve le jardin', max_length=30),
        ),
        migrations.AlterField(
            model_name='lopin',
            name='nom',
            field=models.CharField(help_text='Nom du lopin', max_length=30),
        ),
        migrations.AlterField(
            model_name='plante',
            name='espece',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='plante',
            name='nom',
            field=models.CharField(help_text='Nom de la plante', max_length=30, verbose_name='Nom de la plante'),
        ),
    ]
