# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 07:54
from __future__ import unicode_literals

import apps.jardin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0006_auto_20160427_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jardin',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.jardin.models.content_file_name_jardin),
        ),
    ]
