# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jardin', '0007_auto_20160427_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='jardin',
            name='administrateurs',
            field=models.ManyToManyField(related_name='admin_jardins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jardin',
            name='membres',
            field=models.ManyToManyField(related_name='membre_jardins', to=settings.AUTH_USER_MODEL),
        ),
    ]
