# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0008_auto_20160427_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jardin',
            name='administrateurs',
            field=models.ManyToManyField(related_name='admin_jardins', to='gensdujardin.Profil'),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='membres',
            field=models.ManyToManyField(related_name='membre_jardins', to='gensdujardin.Profil'),
        ),
    ]
