# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0013_auto_20160427_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
