# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0014_auto_20160427_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='espece',
            field=models.CharField(help_text='Nom scientifique de la plante', max_length=50),
        ),
        migrations.AlterField(
            model_name='plante',
            name='nom',
            field=models.CharField(help_text='Nom commun de la plante', max_length=30, verbose_name='Nom de la plante'),
        ),
    ]
