# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0015_auto_20160427_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='jardin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualites', to='jardin.Jardin'),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='adresse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jardins', to='jardin.Adresse'),
        ),
        migrations.AlterField(
            model_name='lopin',
            name='adresse',
            field=models.ForeignKey(help_text="Adresse du lopin. Cette adresse doit être égale à l'adresse du jardin si le lopin se trouve dans un jardin", on_delete=django.db.models.deletion.CASCADE, related_name='lopins', to='jardin.Adresse'),
        ),
        migrations.AlterField(
            model_name='lopin',
            name='jardin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lopins', to='jardin.Jardin'),
        ),
    ]
