# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0016_auto_20160428_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jardin',
            old_name='composter',
            new_name='composteur',
        ),
        migrations.AlterField(
            model_name='plante',
            name='lopin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantes', to='jardin.Lopin'),
        ),
    ]
