# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 22:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0017_auto_20160429_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='code_postal',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Le code postal doit être composé de 5 chiffres.', regex='^\\d{5}$')], verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='long',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='lopin',
            name='adresse',
            field=models.ForeignKey(help_text="Adresse du lopin. Cette adresse doit être égale à l'adresse du jardin si le lopin se trouve dans un jardin", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lopins', to='jardin.Adresse'),
        ),
    ]
