# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0018_auto_20160501_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lopin',
            name='adresse',
            field=models.ForeignKey(help_text='Adresse du lopin indépendant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lopins', to='jardin.Adresse'),
        ),
    ]
