# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0019_auto_20160501_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=7, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='description',
            field=models.TextField(blank=True, default='Pas de description', null=True),
        ),
        migrations.AlterField(
            model_name='lopin',
            name='description',
            field=models.TextField(blank=True, default='Pas de description', null=True),
        ),
        migrations.AlterField(
            model_name='plante',
            name='description',
            field=models.TextField(blank=True, default='Pas de description', null=True),
        ),
    ]
