# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0020_auto_20160502_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='description',
            field=models.TextField(default='Pas de description', null=True),
        ),
    ]
