# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0021_auto_20160502_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='description',
            field=models.TextField(blank=True, default='Pas de description', null=True),
        ),
    ]
