# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin', '0023_jardin_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commun', models.CharField(max_length=200, verbose_name='Le nom commun de la plante')),
                ('scientifique', models.CharField(max_length=200, verbose_name='Le nom scientifique de la plante')),
            ],
        ),
    ]
