# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentairejardin',
            options={'ordering': ['date_creation']},
        ),
        migrations.AlterModelOptions(
            name='commentairelopin',
            options={'ordering': ['date_creation']},
        ),
        migrations.AlterModelOptions(
            name='commentaireplante',
            options={'ordering': ['date_creation']},
        ),
        migrations.RemoveField(
            model_name='commentairejardin',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='commentairelopin',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='commentaireplante',
            name='datetime',
        ),
        migrations.AddField(
            model_name='commentairejardin',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=None, help_text='Date de création du commentaire', verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentairelopin',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=None, help_text='Date de création du commentaire', verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentaireplante',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=None, help_text='Date de création du commentaire', verbose_name='Date de création'),
            preserve_default=False,
        ),
    ]
