# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commentaires', '0002_auto_20160426_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentairejardin',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='commentairelopin',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='commentaireplante',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='commentairejardin',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentairelopin',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentaireplante',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
