# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentaires', '0003_auto_20160427_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentairejardin',
            name='jardin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='jardin.Jardin'),
        ),
        migrations.AlterField(
            model_name='commentairelopin',
            name='lopin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='jardin.Lopin'),
        ),
        migrations.AlterField(
            model_name='commentaireplante',
            name='plante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='jardin.Plante'),
        ),
    ]
