# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gensdujardin', '0001_initial'),
        ('jardin', '0004_auto_20160426_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'action", verbose_name='Date de création')),
                ('lopin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardin.Lopin')),
                ('plante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardin.Plante')),
            ],
        ),
        migrations.CreateModel(
            name='TypeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'action", max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='type_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.TypeAction'),
        ),
        migrations.AddField(
            model_name='action',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gensdujardin.Utilisateur'),
        ),
    ]
