# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='lopin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardin.Lopin'),
        ),
        migrations.AlterField(
            model_name='action',
            name='plante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardin.Plante'),
        ),
    ]
