# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20160427_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='lopin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='jardin.Lopin'),
        ),
        migrations.AlterField(
            model_name='action',
            name='plante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='jardin.Plante'),
        ),
        migrations.AlterField(
            model_name='action',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
