# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20160428_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='type_action',
        ),
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('AR', 'Arroser'), ('PL', 'Planter'), ('RE', 'Retirer'), ('CE', 'Cueillir'), ('FE', 'Fertiliser'), ('EL', 'Elaguer')], default='AR', max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TypeAction',
        ),
    ]
